version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: foodgram-back
    env_file: .env
    build: /backend/
    volumes:
      - media:/app/media/
      - static:/backend_static/

  frontend:
    container_name: foodgram-front
    env_file: .env
    build: /frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/build/

  gateway:
    container_name: foodgram-proxy
    build: /nginx/
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - media:/media
      - static:/static
    depends_on:
      - backend
      - frontend

