# Generated by Django 3.2.3 on 2024-10-18 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Количество ингредиента не может быть меньше 0.1 г/мл')], verbose_name='Количество ингредиента'),
        ),
    ]
