# Generated by Django 3.2.3 on 2024-10-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Короткая ссылка на рецепт'),
        ),
    ]
